### ISSUE TITLE
'Talisman of nourishment' causing internal server error

### ISSUE THREAD

**Issue by thcv** [nekosune/Thaumic_Exploration#21]
This is the error I was asked to post:

java.lang.ClassCastException: flaxbeard.thaumicexploration.misc.FakePlayerPotion cannot be cast to net.minecraft.entity.player.EntityPlayerMP

**Comment by nekosune** [comment]
I need the full error please, not just the first line, the whole log would help

**Comment by mrdeadlocked** [comment]
That is all that it shows server side.. The server does not crash. It only kicks that player off the server.

**Comment by nekosune** [comment]
that is the first line of an error, the error usually looks like this: http://pastebin.com/318AqhcB

**Comment by thcv** [comment]
I (the client) did not get a crash report either.

**Comment by nekosune** [comment]
There is still going to be more error then that, what is on the lines under and over the one given?

**Comment by piotrb** [comment]
Hey,

Just got this issue ...

Here is the details

```
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:464) ~[mw.class:?]
        at api.player.server.ServerPlayerAPI.onUpdateEntity(ServerPlayerAPI.java:4828) ~[ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:498) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) ~[jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassCastException: flaxbeard.thaumicexploration.misc.FakePlayerPotion cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at net.minecraft.util.FoodStats.func_151686_a(FoodStats.java:52) ~[zr.class:?]
        at net.minecraft.item.ItemFood.func_77654_b(SourceFile:36) ~[acx.class:?]
        at flaxbeard.thaumicexploration.item.ItemFoodTalisman.isEdible(ItemFoodTalisman.java:135) ~[ItemFoodTalisman.class:?]
        at flaxbeard.thaumicexploration.item.ItemFoodTalisman.func_77663_a(ItemFoodTalisman.java:68) ~[ItemFoodTalisman.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:440) ~[add.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:386) ~[yx.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:622) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localOnLivingUpdate(EntityPlayerMP.java) ~[mw.class:?]
        at api.player.server.ServerPlayerAPI.onLivingUpdate(ServerPlayerAPI.java:4608) ~[ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70636_d(EntityPlayerMP.java) ~[mw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1869) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:316) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:393) ~[mw.class:?]
        ... 12 more
```

**Comment by nekosune** [comment]
Okay thankyou, do you have any idea what edible items where in inventory?
The trouble with this is it was trying to eat something it cant, but to fix
I need to know WHICH item, so I can blacklist it from trying to eat it again

**Comment by piotrb** [comment]
I don't think its that simple ..

When I had no food items it was ok, when I added a single baked potato .. boom .. 

Potatoes are definitely edible ...

**Comment by piotrb** [comment]
There wasn't .. there was one line above it basically saying that it failed handling the data packet for the client's IP address, other than that the usual server stuff

This specifically happens on the server side, and then it kicks out the client, no hard crash per say.

**Comment by nekosune** [comment]
Which versions of which things? Forge, TC and TX please,

**Comment by nekosune** [comment]
Looking at this, I have an idea of what MAY fix it, just got to test it,
this is thanks to apparently minecraft trying to track stats for even fake
players eating food

**Comment by piotrb** [comment]
Forge: 7.10.85.1236
TC: 4.2.2.1
TX: latest jenkins (build 36)

**Comment by piotrb** [comment]
Is the talisman pretending to eat the food to figure out how much nourishment it gives or something?

**Comment by nekosune** [comment]
It has to have a fake player eat the food, because of the amount of edibles that add potion effects,  like for example thaumcraft's three meat thing or do other stuff, something that the talisman rejects. it has the fake player 'eat' the food, then checks said fake player for potion effects. Turns out on servers it can get confused about that, hence why am working on a fix to make it more server compliant as it does it.

**Comment by davidlohle** [comment]
Heya, is there any update for this issue?
