### ISSUE TITLE
Incompatibility with REI's minimap

### ISSUE THREAD

**Issue by LemADEC** [nekosune/Thaumic_Exploration#33]
When we add Thaumic Exploration, REI's minimap will no longer show up in game.
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.7.10-1.1.3.140-universal
CodeChickenCore-1.7.10-1.0.7.47-universal
Thaumcraft-1.7.10-4.2.3.5
ThaumicExploration-1.7.10-1.1-53
Reis-Minimap-Mod-1.7.10-3.6

Any idea what's causing this?

**Comment by GaeaKat** [comment]
Can I get a full client log,  as this doesn't appear to be reproducible

**Comment by LemADEC** [comment]
I've forgot to specify Forge Mod Loader version 7.99.39.1566 for Minecraft 1.7.10.
Logs are attached with and without Thaumic Exploration added.
It seems TE is adding a codechicken.core.launch.DepLoader in addition to the one from Thaumcraft.
Also, there's a crash in NEI when TE is present:

```
[03:44:25] [Client thread/DEBUG] [FML/]: Bar Finished: Loading Resource - ReiMinimap took 0,085s
[03:44:26] [Thread-13/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArithmeticException: / by zero
[03:44:26] [Thread-13/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at reifnsk.minimap.BlockDataPack.calcColorArrays(BlockDataPack.java:551)
[03:44:26] [Thread-13/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at reifnsk.minimap.BlockDataPack.calcTextureColor(BlockDataPack.java:143)
[03:44:26] [Thread-13/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at reifnsk.minimap.BlockDataPack.access$000(BlockDataPack.java:32)
[03:44:26] [Thread-13/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at reifnsk.minimap.BlockDataPack$1.run(BlockDataPack.java:91)
```

[fml-client-latest with ThaumicExploration, not working.txt](https://github.com/nekosune/Thaumic_Exploration/files/75842/fml-client-latest.with.ThaumicExploration.not.working.txt)
[fml-client-latest without ThaumicExploration, REI showing.txt](https://github.com/nekosune/Thaumic_Exploration/files/75843/fml-client-latest.without.ThaumicExploration.REI.showing.txt)

**Comment by GaeaKat** [comment]
Will go through and see if can be reproduced with those version numbers,  and if so what can do to fix as soon as I have built my computer

**Comment by LemADEC** [comment]
Any success on building your computer?
